import "bootstrap";
import "components/autocomplete";
import { amamazingPopOver } from "components/popover";
amamazingPopOver();
// import "components/random_generator";
import { amazingConfirmation } from "components/jquery_confirmation";
amazingConfirmation();
import { addToSl } from "components/jquery_confirmation";
addToSl();
import { sendEmailSL } from "components/jquery_confirmation";
sendEmailSL();
import { startCookingMode } from "components/jquery_confirmation";
startCookingMode();
